---
title: "Untitled"
author: "MG"
date: "2023-05-24"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(car)
```

```{r}
temp = read.csv("output/viral_host_sharing_G_df1.csv", header = T)
for(i in 2:127){
  temp = rbind(temp, read.csv(paste("output/viral_host_sharing_G_df",i,".csv",sep = ""), header = T))
}
str(temp)
temp = temp[,-1]
write.csv(temp,"output/viral_host_sharing_G_df.csv")

temp = read.csv("output/intraOrder_importance_df1.csv", header = T)
for(i in 2:127){
  temp = rbind(temp, read.csv(paste("output/intraOrder_importance_df",i,".csv",sep = ""), header = T))
}
str(temp)
temp = temp[,-1]
write.csv(temp,"output/intraOrder_importance_df.csv")
```

```{r}
main_theme = theme_bw()+
  theme(line = element_blank(), 
        axis.line = element_line(colour = "black"),
        panel.border = element_blank(),
        axis.ticks =  element_line(colour = "black"),
        axis.text.x = element_text(colour = "black", size=17),
        axis.text.y = element_text(colour = "black", size=17),
        legend.title = element_text(colour = "black", size=17),
        legend.text = element_text(colour = "black", size=15),
        axis.title=element_text(size=15))
```

```{r}
intraOrder_importance_df = read.csv("output/intraOrder_importance_df.csv", header = T,
                                    stringsAsFactors = T)
intraOrder_importance_df = intraOrder_importance_df[,-1]
str(intraOrder_importance_df)
clover = read.csv("data/clover.csv", header = T,
                                    stringsAsFactors = T)

intraOrder_importance_df$zeta_HostOrder_location = ifelse(as.character(intraOrder_importance_df$HostOrder)==
                                             as.character(intraOrder_importance_df$HostOrder_zeta),
                                           "intra", "extra")
intraOrder_importance_df$zeta_VirusOrder_location = ifelse(as.character(intraOrder_importance_df$VirusOrder)==
                                             as.character(intraOrder_importance_df$VirusOrder_zeta),
                                           "intra", "extra")
str(intraOrder_importance_df)
ggplot(intraOrder_importance_df)+
  geom_boxplot(aes(HostOrder,score_global_h))+
  facet_wrap(~HostOrder_zeta)+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))
inra_vs_extra_subset = intraOrder_importance_df%>%
  select(c("HostOrder_zeta","HostOrder_score","host_zeta" ,"score_extra_order_h",
          "complet_score", "zeta_HostOrder_location", "X"))%>%
  filter(zeta_HostOrder_location =="intra")%>%
  select(-c( "zeta_HostOrder_location"))%>%
  pivot_longer(c(HostOrder_score,score_extra_order_h,complet_score), names_to = "score_location", values_to = "score")
str(inra_vs_extra_subset)
inra_vs_extra_subset$score_location = as.factor(inra_vs_extra_subset$score_location)
levels(inra_vs_extra_subset$score_location) = levels =c("all", "intra", "extra")

interaction_ID = inra_vs_extra_subset%>%
  group_by(HostOrder_zeta)%>%
  filter(score_location == "all")%>%
  arrange(score)%>%
  slice(1:50)%>%
  pull(X)
inra_vs_extra_subset%>%
  filter(X %in% interaction_ID)%>%
ggplot()+
  geom_boxplot(aes(HostOrder_zeta, score, col = score_location))+
  color_palette("pastel1")+
  labs(col =c("score location") )+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))

str(viral_host_sharing_G_df)
inra_vs_extra_sharing_subset = viral_host_sharing_G_df%>%
  select(c("HostOrder_zeta","score_intra_h","host_zeta" ,"score_extra_order_h",
          "complet_score", "zeta_HostOrder_location", "X"))%>%
  filter(zeta_HostOrder_location =="intra")%>%
  select(-c( "zeta_HostOrder_location"))%>%
  pivot_longer(c(score_intra_h,score_extra_order_h,complet_score), names_to = "score_location", values_to = "score")
str(inra_vs_extra_sharing_subset)
inra_vs_extra_sharing_subset$score_location = as.factor(inra_vs_extra_sharing_subset$score_location)
levels(inra_vs_extra_sharing_subset$score_location) = levels =c("all", "extra", "intra")

interaction_ID2 = inra_vs_extra_sharing_subset%>%
  group_by(HostOrder_zeta)%>%
  filter(score_location == "all")%>%
  arrange(score)%>%
  slice(1:50)%>%
  pull(X)
inra_vs_extra_sharing_subset%>%
  filter(X %in% interaction_ID2)%>%
ggplot()+
  geom_boxplot(aes(HostOrder_zeta, score, col = score_location))+
  color_palette("pastel1")+
  labs(col =c("score location") )+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))
```

```{r}
ggplot(intraOrder_importance_df, aes(complet_score,HostOrder_score))+
  geom_point()+
  geom_abline(intercept= 0, slope = 1, "blue")+
  main_theme
```

```{r}

### 50 most impactfull modification wtih respect to host order and location of impacte (intra or extra order)
intraOrder_importance_df=intraOrder_importance_df%>%
  arrange(HostOrder_score)
intraOrder_importance_df$n = c(1:nrow(intraOrder_importance_df))

ggplot(intraOrder_importance_df)+
  geom_point(aes(n,HostOrder_score))
### mean between extra, in order to not selelts extra that have most impact when silicing
# geom_density to show the need of means
intraOrder_importance_df%>%
  group_by(HostOrder,zeta_pos)%>%
  arrange(HostOrder_score)%>%
  slice(1:50)%>%
ggplot()+
  geom_bar(aes(HostOrder_zeta, col = zeta_pos))+
  facet_wrap(~HostOrder)
intraOrder_importance_df%>%
  group_by(HostOrder_zeta,zeta_pos)%>%
  count()
intraOrder_importance_df%>%
  group_by(HostOrder_zeta,zeta_pos)
intraOrder_importance_df%>%
  group_by(HostOrder_zeta,zeta_pos)%>%
  arrange(HostOrder_score)%>%
  slice(1:50)%>%
  #filter(HostOrder_zeta =="Chiroptera")%>%
ggplot()+
  geom_bar(aes(HostOrder, fill=zeta_pos))+
  facet_wrap(~HostOrder_zeta)+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))

intraOrder_importance_df%>%
  group_by(HostOrder_zeta,zeta_pos)%>%
  arrange(HostOrder_score)%>%
  slice(1:50)%>%
  ggplot()+
  geom_boxplot(aes(HostOrder_zeta,HostOrder_score, col = zeta_pos))+
  geom_point(aes(HostOrder_zeta,HostOrder_score, col = zeta_pos))+
  geom_jitter(aes(HostOrder_zeta,HostOrder_score, col = zeta_pos))+
  main_theme

intraOrder_importance_df = intraOrder_importance_df%>%
   group_by(host_zeta,virus_zeta,zeta_pos)%>%
  mutate(mean_h_score  = mean(HostOrder_score))
str(intraOrder_importance_df)

intraOrder_max_subset = intraOrder_importance_df%>%
  group_by(HostOrder,zeta_pos)%>%
  arrange(mean_h_score)%>%
  slice(1:50)

# intraOrder_max_subset = intraOrder_importance_df%>%
#   arrange(HostOrder_score)%>%
#   slice(1:700)
str(intraOrder_importance_df)
intraOrder_max_subset[intraOrder_max_subset$HostOrder == "Chiroptera",]

ggplot(intraOrder_max_subset)+
  geom_boxplot(aes(HostOrder,mean_h_score,col =zeta_pos),cex=2)+
  #geom_point(aes(HostOrder,HostOrder_score, col =zeta_pos), cex=2, alpha = 0.2)+
  labs(y= "z-score of the modification", col = "Host Order location of impact")+
  color_palette("pastel1")+
  main_theme



mod_hostorder1 = lm(HostOrder_score~zeta_pos, data=intraOrder_max_subset)
mod_hostorder2 = lm(HostOrder_score~HostOrder, data=intraOrder_max_subset)
mod_hostorder3 = lm(HostOrder_score~HostOrder*zeta_pos, data=intraOrder_max_subset)
plot(mod_hostorder3)
hist(mod_hostorder3$residuals)
anova(mod_hostorder1,mod_hostorder2, mod_hostorder3)

AIC(mod_hostorder1)
AIC(mod_hostorder2)
AIC(mod_hostorder3)
Anova(mod_hostorder3,type ="II")
summary(mod_hostorder3)
TukeyHSD(aov(mod_hostorder3))
```
### Proof of concept : wich order Primates impact have most impact on ?
```{r}
str(intraOrder_importance_df)
intraOrde_primate_subset = intraOrder_importance_df%>%
  filter(HostOrder_zeta == "Chiroptera")%>%
  arrange(HostOrder_score)%>%
  slice(1:1000)

ggplot(intraOrde_primate_subset)+
  geom_boxplot(aes(HostOrder,HostOrder_score),cex=2)+
  #geom_point(aes(HostOrder,HostOrder_score, col =zeta_pos), cex=2, alpha = 0.2)+
  labs(y= "z-score of the modification", col = "Host Order location of impact")+
  color_palette("pastel1")+
  main_theme


```

##### Host viral sharing with communicabity
```{r}
viral_host_sharing_G_df = read.csv("output/viral_host_sharing_G_df.csv", header = T,
                                   stringsAsFactors = T)

str(viral_host_sharing_G_df)
viral_host_sharing_G_df = viral_host_sharing_G_df[,-1]


viral_host_sharing_G_df$zeta_HostOrder_location = ifelse(as.character(viral_host_sharing_G_df$HostOrder)==
                                             as.character(viral_host_sharing_G_df$HostOrder_zeta),
                                           "intra", "extra")
viral_host_sharing_G_df$zeta_VirusOrder_location = ifelse(as.character(viral_host_sharing_G_df$VirusOrder)==
                                             as.character(viral_host_sharing_G_df$VirusOrder_zeta),
                                           "intra", "extra")
viral_host_sharing_G_df%>%
  filter(HostOrder == "Primates")%>%
ggplot()+
  geom_boxplot(aes(HostOrder_zeta,score_global_h))+
  #facet_wrap(~HostOrder)+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))
ggplot(viral_host_sharing_G_df)+
  geom_boxplot(aes(HostOrder,score_intra_h,))+
  facet_wrap(~HostOrder_zeta)+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))
ggplot(viral_host_sharing_G_df)+
  geom_boxplot(aes(HostOrder_zeta,complet_score))+
  #facet_wrap(~HostOrder)+
  main_theme+
  theme(axis.text.x = element_text(angle =45, hjust = 1))


str(viral_host_sharing_G_df)

g1 = viral_host_sharing_G_df%>%
  group_by(HostOrder,HostOrder_zeta)%>%
  arrange(score_intra_h)%>%
  slice(1:50)%>%
ggplot()+
  geom_boxplot(aes(HostOrder, score_intra_h, col = zeta_HostOrder_location))+
  #facet_wrap(~HostOrder_zeta)+
  color_palette("pastel1")+
  main_theme+
  theme(axis.text.x = element_blank(),
        axis.title.x  = element_blank())
str(viral_host_sharing_G_df)
g2 = viral_host_sharing_G_df%>%
  group_by(HostOrder,HostOrder_zeta)%>%
  arrange(score_intra_h)%>%
  slice(1:50)%>%
ggplot()+
  geom_boxplot(aes(HostOrder_zeta, score_intra_h, col = zeta_HostOrder_location))+
  #facet_wrap(~HostOrder_zeta)+
  color_palette("pastel1")+
  main_theme+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title = element_blank())

g3 = intraOrder_importance_df%>%
  group_by(HostOrder,HostOrder_zeta)%>%
  arrange(HostOrder_score)%>%
  #slice(1:50)%>%
ggplot()+
  geom_boxplot(aes(HostOrder, HostOrder_score, col = zeta_HostOrder_location))+
  #facet_wrap(~HostOrder_zeta)+
  color_palette("pastel1")+
  main_theme+
  theme(axis.text.x = element_text(colour = "black", size=12,angle =45, hjust = 1))
str(intraOrder_importance_df)
intraOrder_importance_df%>%
  group_by(HostOrder_zeta)%>%
  arrange(complet_score)%>%
  slice(1:100)%>%
  count(zeta_HostOrder_location)
g4 = intraOrder_importance_df%>%
  group_by(HostOrder_zeta)%>%
  arrange(complet_score)%>%
  slice(1:100)%>%
ggplot()+
  geom_boxplot(aes(HostOrder, HostOrder_score, col = zeta_HostOrder_location))+
  #facet_wrap(~HostOrder)+
  color_palette("pastel1")+
  main_theme+
  theme(axis.text.x = element_text(colour = "black", size=12,angle =45, hjust = 1))
,
        axis.text.y = element_blank(),
        axis.title.y  = element_blank())
ggarrange(g1,g2,g3,g4,nrow = 2,ncol = 2, labels = c("are Impacted", "impact"))
head(viral_host_sharing_G_df)
viral_host_sharing_G_df=viral_host_sharing_G_df%>%
  arrange(HostOrder_score)
viral_host_sharing_G_df$n = c(1:nrow(viral_host_sharing_G_df))

ggplot(viral_host_sharing_G_df)+
  geom_density(aes(score_extra_intra_h))

str(viral_host_sharing_G_df)
viral_host_sharing_G_df = viral_host_sharing_G_df%>%
   group_by(host_zeta,virus_zeta,zeta_pos)%>%
  mutate(mean_h_score  = mean(score_intra_h))


host_sharing_max_subset = viral_host_sharing_G_df%>%
  group_by(HostOrder,zeta_pos)%>%
  arrange(mean_h_score)%>%
  slice(1:50)

ggplot(viral_host_sharing_G_df)+
  geom_boxplot(aes(HostOrder,score_intra_h,col =zeta_pos),cex=2)+

  labs(y= "Host sharing (with G)", col = "link removal (Host Order)")+
  color_palette("pastel1")+
  main_theme+
  theme(axis.text.x = element_text(colour = "black", size=12,angle =45, hjust = 1))

ggplot(host_sharing_max_subset)+
  geom_boxplot(aes(HostOrder,mean_h_score,col =zeta_pos),cex=2)+
  labs(y= "Host sharing (with G)", col = "link removal (Host Order)")+
  color_palette("pastel1")+
  main_theme+
  theme(axis.text.x = element_text(colour = "black", size=12,angle =45, hjust = 1))

viral_host_sharing_G_df%>%
  filter(HostOrder_zeta %in% levels(HostOrder))%>%
  group_by(HostOrder_zeta,HostOrder)%>%
  arrange(score_intra_h)%>%
  slice(1:50)%>%
ggplot()+
  geom_boxplot(aes(HostOrder,score_intra_h, col = zeta_pos),cex=2)+
  facet_wrap(~HostOrder_zeta)+
  labs(y= "Host sharing (with G)", col = "link removal (Host Order)")+
  main_theme+
  theme(axis.text.x = element_text(colour = "black", size=12,angle =45, hjust = 1))
viral_host_sharing_G_df%>%
  filter(HostOrder_zeta %in% levels(HostOrder))%>%
  ggplot()+
  geom_bar(aes(HostOrder, col = zeta_pos))+
  facet_wrap(~HostOrder_zeta)


ggplot(viral_host_sharing_G_df)+
  geom_boxplot(aes(HostOrder,score_extra_intra_h,col =zeta_pos),cex=2)+

  labs(y= "Host sharing (with G)", col = "link removal (Host Order)")+
  color_palette("pastel1")+
  main_theme
```



##### Test with data from Albery 2020
```{r}
# data setup
load("data/Finaldf.Rdata")
load("data/AllPredictions1b.Rdata")
load("data/BAMList.Rdata")
names(BAMList[["VirusBinary"]])
names(AllPredictions1b)
head(AllPredictions1b[[1]])
head(FinalHostMatrix)
FinalHostMatrix = FinalHostMatrix[names(FinalHostMatrix) %in% c("Sp", "Sp2","hOrder.Sp2",
                                                                "hOrder","VirusBinary","Phylo")]
FinalHostMatrix$hOrder = as.factor(FinalHostMatrix$hOrder)
FinalHostMatrix$hOrder.Sp2 = as.factor(FinalHostMatrix$hOrder.Sp2)
levels(viral_host_sharing_G_df$HostOrder)
levels(FinalHostMatrix$hOrder.Sp2) = c("Carnivora","Cetartiodactyla","Chiroptera","a","Eulipotyphla","Lagomorpha","Perissodactyla","c","Primates","d","Rodentia")
levels(FinalHostMatrix$hOrder) = c("Carnivora","Cetartiodactyla","Chiroptera","a","Eulipotyphla","Lagomorpha",
                                   "Perissodactyla","c","Primates","d","Rodentia")
head(FinalHostMatrix)
str(FinalHostMatrix)
### select order
FinalHostMatrix = FinalHostMatrix[as.character(FinalHostMatrix$hOrder) %in% 
                     levels(viral_host_sharing_G_df$HostOrder) &
                     as.character(FinalHostMatrix$hOrder.Sp2) %in% levels(viral_host_sharing_G_df$HostOrder),]
levels(FinalHostMatrix$Sp) = gsub("_"," ", levels(FinalHostMatrix$Sp))
levels(FinalHostMatrix$Sp2) = gsub("_"," ", levels(FinalHostMatrix$Sp2))
### select corresponding species
ID1 = which(FinalHostMatrix$Sp %in% viral_host_sharing_G_df$host_zeta)
length(ID1) ; length(FinalHostMatrix$Sp)
ID2 = which(viral_host_sharing_G_df$host_zeta %in% FinalHostMatrix$Sp)
length(ID2) ; length(viral_host_sharing_G_df$host_zeta)
FinalHostMatrix = FinalHostMatrix[-ID1,]
viral_host_sharing_G_subset = viral_host_sharing_G_df[-ID2,]
str(FinalHostMatrix)

FinalHostMatrix%>%
  group_by(hOrder,hOrder.Sp2)%>%
  count()%>%
ggplot()+
  geom_bar(aes(hOrder,n), stat = "identity")+
  facet_wrap(~hOrder.Sp2)+
    main_theme+
  theme(axis.text.x = element_text(colour = "black", size=12,angle =45, hjust = 1))
```


